// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpxzlprwcailqnftihyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZweHpscHJ3Y2FpbHFuZnRpaHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTk1NzQsImV4cCI6MjA1NTY5NTU3NH0.Opa8puEbliyynAVypkp1R5vRV8kL6P3pZeuDsaf83s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);